version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-default_db}
      POSTGRES_USER: ${DB_USER:-db_user}
      POSTGRES_PASSWORD: ${DB_PASS:-db_Passw0rD}

volumes:
  postgres:

networks:
  postgres:
    driver: bridge
